### ISSUE TITLE
`libsass` bindings not found. Try reinstalling `node-sass`?

### ISSUE THREAD

**Issue by teckays** [unionups/ember-cli-bootstrap-sass#18]
I have this error here after installing your library. To mention that I use `scss` myself for the project, and everything compiles just fine without `ember-cli-bootstrap-sass`.

**Stack**

```
$ ember serve
`libsass` bindings not found. Try reinstalling `node-sass`?
Error: `libsass` bindings not found. Try reinstalling `node-sass`?
    at getBinding (/Users/username/Project/cs-web/client/node_modules/ember-cli-bootstrap-sass/node_modules/node-sass/lib/index.js:22:11)
    at Object.<anonymous> (/Users/username/Project/cs-web/client/node_modules/ember-cli-bootstrap-sass/node_modules/node-sass/lib/index.js:188:23)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/username/Project/cs-web/client/node_modules/ember-cli-bootstrap-sass/node_modules/broccoli-sass-source-maps/index.js:5:12)
    at Module._compile (module.js:397:26)
```

**Comment by GiovanniL19** [comment]
Has anyone had any luck with this?

**Comment by kwekut** [comment]
The sass dependency for this project is expired. Please use alternative
 "ember install ember-cli-bootstrap-sassy".

Or else fork this project, then go to its package.json and change the dependencies, 
 "dependencies": {
    "ember-cli-sass": "your version here"
  },
then install your forked via 
"ember install https://github.com/<repo-username>/<repo-name>.git"
